[package]
name = "date-time"
version = "1.0.1"
description = "The date-time Mops package provides comprehensive utilities for date and time manipulation in Motoko, including creation, formatting, arithmetic, comparison, and timezone handling without relying on the Time package."
repository = "https://github.com/toshakparmar/date-time-motoko"
keywords = [
  "date-time",
  "date-time-motoko",
  "motoko-date",
  "motoko-time"
]
license = "MIT"

[dependencies]
base = "0.14.1"